// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using primerParcial.Models;

namespace primerParcial.Migrations
{
    [DbContext(typeof(MworoutineDbContext))]
    [Migration("20210712174812_cuerpoaejer")]
    partial class cuerpoaejer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("primerParcial.Models.Actividad", b =>
                {
                    b.Property<int>("EjercicioId")
                        .HasColumnType("int");

                    b.Property<int?>("DiaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cantRepeticiones")
                        .HasColumnType("int");

                    b.Property<int>("cantSeries")
                        .HasColumnType("int");

                    b.HasKey("EjercicioId");

                    b.HasIndex("DiaId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("primerParcial.Models.Cliente", b =>
                {
                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("EntrenadorTrainerId")
                        .HasColumnType("int");

                    b.Property<string>("FotoRuta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ObjetivoId")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<DateTime>("fechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaNac")
                        .HasColumnType("datetime2");

                    b.HasKey("DNI");

                    b.HasIndex("EntrenadorTrainerId");

                    b.HasIndex("ObjetivoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("primerParcial.Models.Dia", b =>
                {
                    b.Property<int>("DiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("int");

                    b.HasKey("DiaId");

                    b.HasIndex("RutinaId");

                    b.ToTable("Dias");
                });

            modelBuilder.Entity("primerParcial.Models.Ejercicio", b =>
                {
                    b.Property<int>("EjercicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MusculoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParteDelCuerpoId")
                        .HasColumnType("int");

                    b.Property<string>("Urlvideo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjercicioId");

                    b.HasIndex("MusculoId");

                    b.HasIndex("ParteDelCuerpoId");

                    b.ToTable("Ejercicios");
                });

            modelBuilder.Entity("primerParcial.Models.Musculo", b =>
                {
                    b.Property<int>("MusculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParteDelCuerpoId")
                        .HasColumnType("int");

                    b.HasKey("MusculoId");

                    b.HasIndex("ParteDelCuerpoId");

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("primerParcial.Models.Objetivo", b =>
                {
                    b.Property<int>("ObjetivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjetivoId");

                    b.ToTable("Objetivos");
                });

            modelBuilder.Entity("primerParcial.Models.ParteDelCuerpo", b =>
                {
                    b.Property<int>("ParteDelCuerpoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParteDelCuerpoId");

                    b.ToTable("PartesDelCuerpo");
                });

            modelBuilder.Entity("primerParcial.Models.PersonalTrainer", b =>
                {
                    b.Property<int>("TrainerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainerId");

                    b.ToTable("Entrenadores");
                });

            modelBuilder.Entity("primerParcial.Models.Rutina", b =>
                {
                    b.Property<int>("RutinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteDNI")
                        .HasColumnType("int");

                    b.Property<int>("cantDiasporSemana")
                        .HasColumnType("int");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("RutinaId");

                    b.HasIndex("ClienteDNI");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("primerParcial.Models.Actividad", b =>
                {
                    b.HasOne("primerParcial.Models.Dia", "Dia")
                        .WithMany("Actividades")
                        .HasForeignKey("DiaId");

                    b.HasOne("primerParcial.Models.Ejercicio", "Ejercicio")
                        .WithOne("Actividad")
                        .HasForeignKey("primerParcial.Models.Actividad", "EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dia");

                    b.Navigation("Ejercicio");
                });

            modelBuilder.Entity("primerParcial.Models.Cliente", b =>
                {
                    b.HasOne("primerParcial.Models.PersonalTrainer", "Entrenador")
                        .WithMany("Clientes")
                        .HasForeignKey("EntrenadorTrainerId");

                    b.HasOne("primerParcial.Models.Objetivo", "Objetivo")
                        .WithMany("Clientes")
                        .HasForeignKey("ObjetivoId");

                    b.Navigation("Entrenador");

                    b.Navigation("Objetivo");
                });

            modelBuilder.Entity("primerParcial.Models.Dia", b =>
                {
                    b.HasOne("primerParcial.Models.Rutina", "Rutina")
                        .WithMany("Dias")
                        .HasForeignKey("RutinaId");

                    b.Navigation("Rutina");
                });

            modelBuilder.Entity("primerParcial.Models.Ejercicio", b =>
                {
                    b.HasOne("primerParcial.Models.Musculo", "Musculo")
                        .WithMany("Ejercicios")
                        .HasForeignKey("MusculoId");

                    b.HasOne("primerParcial.Models.ParteDelCuerpo", "ParteDelCuerpo")
                        .WithMany()
                        .HasForeignKey("ParteDelCuerpoId");

                    b.Navigation("Musculo");

                    b.Navigation("ParteDelCuerpo");
                });

            modelBuilder.Entity("primerParcial.Models.Musculo", b =>
                {
                    b.HasOne("primerParcial.Models.ParteDelCuerpo", null)
                        .WithMany("Musculo")
                        .HasForeignKey("ParteDelCuerpoId");
                });

            modelBuilder.Entity("primerParcial.Models.Rutina", b =>
                {
                    b.HasOne("primerParcial.Models.Cliente", "Cliente")
                        .WithMany("Rutinas")
                        .HasForeignKey("ClienteDNI");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("primerParcial.Models.Cliente", b =>
                {
                    b.Navigation("Rutinas");
                });

            modelBuilder.Entity("primerParcial.Models.Dia", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("primerParcial.Models.Ejercicio", b =>
                {
                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("primerParcial.Models.Musculo", b =>
                {
                    b.Navigation("Ejercicios");
                });

            modelBuilder.Entity("primerParcial.Models.Objetivo", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("primerParcial.Models.ParteDelCuerpo", b =>
                {
                    b.Navigation("Musculo");
                });

            modelBuilder.Entity("primerParcial.Models.PersonalTrainer", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("primerParcial.Models.Rutina", b =>
                {
                    b.Navigation("Dias");
                });
#pragma warning restore 612, 618
        }
    }
}
